// Generated by https://quicktype.io

export interface ChannelFull {
    window:      number;
    version:     number;
    timestamp:   number;
    api_warning: string;
    body:        Details;
}

export interface Details {
    channel: Channel;
}

export interface Channel {
    id:                    number | undefined;
    channel_id:            number;
    stream_id:             number;
    submission_style:      string;
    channel_style:         string;
    public_read:           boolean;
    writable:              boolean;
    parent_channel_id:     null;
    created_at:            string;
    updated_at:            string;
    title:                 string;
    description:           string;
    formatted_description: string;
    urls:                  Urls;
    category:              Category;
    channel_clips_count:   number;
    total_plays:           number;
}

export interface Category {
    id:          number;
    title:       string;
    description: null;
    updated_at:  string;
    priority:    number;
}

export interface Urls {
    web_url:      string;
    logo_image:   Image;
    banner_image: Image;
}

export interface Image {
    original: string;
}
